export interface FlutterwaveDeps {
  secretKey: string;
  fetchImpl?: typeof fetch;
  /** Overridable for tests; defaults to Flutterwave's real v3 API. */
  apiBaseUrl?: string;
}

export class FlutterwaveApiError extends Error {}

export interface CreatePaymentLinkParams {
  txRef: string;
  /** Major-unit decimal string (e.g. "5000.00" NGN, never minor-unit kobo) — Flutterwave's Standard Checkout expects major units. */
  amount: string;
  currency: string;
  customerEmail: string;
  customerPhoneNumber: string;
  redirectUrl: string;
  title: string;
}

/**
 * Creates a Flutterwave Standard Checkout hosted payment link
 * (`POST /v3/payments`). `txRef` is generated by the caller (domain/payments.ts)
 * rather than by Flutterwave, so it's available to store on the Invoice row
 * before the checkout link is even requested — Flutterwave echoes it back
 * unchanged on both the webhook payload and the Verify Transaction response,
 * which is what lets confirmSubscriptionPayment reconcile either one back to
 * this Invoice.
 */
export async function createFlutterwavePaymentLink(
  deps: FlutterwaveDeps,
  params: CreatePaymentLinkParams,
): Promise<{ checkoutUrl: string }> {
  const fetchFn = deps.fetchImpl ?? fetch;
  const baseUrl = deps.apiBaseUrl ?? "https://api.flutterwave.com/v3";

  const response = await fetchFn(`${baseUrl}/payments`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${deps.secretKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      tx_ref: params.txRef,
      amount: params.amount,
      currency: params.currency,
      redirect_url: params.redirectUrl,
      customer: { email: params.customerEmail, phonenumber: params.customerPhoneNumber },
      customizations: { title: params.title },
    }),
  });

  if (!response.ok) {
    const body = await response.text();
    throw new FlutterwaveApiError(`Flutterwave payment-link creation failed (${response.status}): ${body}`);
  }

  const json = (await response.json()) as { status?: string; data?: { link?: string } };
  if (json.status !== "success" || !json.data?.link) {
    throw new FlutterwaveApiError(`Flutterwave payment-link creation returned an unexpected response: ${JSON.stringify(json)}`);
  }

  return { checkoutUrl: json.data.link };
}

export interface VerifiedFlutterwaveTransaction {
  status: string; // "successful" | "failed" | ... — Flutterwave's own vocabulary, passed through as-is
  amount: number; // major units, as Flutterwave returns it
  currency: string;
  txRef: string;
}

/**
 * Server-to-server "Verify Transaction" call (`GET /v3/transactions/:id/verify`).
 * Per Flutterwave's own integration guidance, the webhook payload is not
 * cryptographically signed over its content (unlike WhatsApp's HMAC — see
 * whatsapp/signature.ts) — the shared-secret `verif-hash` header only proves
 * the request came from Flutterwave, not that the payload wasn't tampered
 * with in transit. This call is what confirmSubscriptionPayment actually
 * trusts for status/amount/currency, never the webhook body directly.
 */
export async function verifyFlutterwaveTransaction(
  deps: FlutterwaveDeps,
  transactionId: string,
): Promise<VerifiedFlutterwaveTransaction> {
  const fetchFn = deps.fetchImpl ?? fetch;
  const baseUrl = deps.apiBaseUrl ?? "https://api.flutterwave.com/v3";

  const response = await fetchFn(`${baseUrl}/transactions/${transactionId}/verify`, {
    method: "GET",
    headers: { Authorization: `Bearer ${deps.secretKey}` },
  });

  if (!response.ok) {
    const body = await response.text();
    throw new FlutterwaveApiError(`Flutterwave transaction verification failed (${response.status}): ${body}`);
  }

  const json = (await response.json()) as {
    status?: string;
    data?: { status?: string; amount?: number; currency?: string; tx_ref?: string };
  };
  if (json.status !== "success" || !json.data) {
    throw new FlutterwaveApiError(`Flutterwave transaction verification returned an unexpected response: ${JSON.stringify(json)}`);
  }

  return {
    status: json.data.status ?? "unknown",
    amount: json.data.amount ?? 0,
    currency: json.data.currency ?? "",
    txRef: json.data.tx_ref ?? "",
  };
}
